openapi: 3.0.4
info:
  title: Exchange Rate
  description: Exchange Rate is a simple tool for getting the current exchange rate between two currencies. It returns the current exchange rate.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/exchangerate:
    get:
      summary: Get Exchange Rate
      description: Exchange Rate is a simple tool for getting the current exchange rate between two currencies. It returns the current exchange rate.
      operationId: exchangerate
      parameters:
      - name: currency1
        in: query
        schema:
          type: string
        required: true
        description: The first currency you want to get the exchange rate for (e.g. USD)
        example: USD
      - name: currency2
        in: query
        schema:
          type: string
        required: true
        description: The second currency you want to get the exchange rate for (e.g. EUR)
        example: EUR
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  currency1: USD
                  currency2: EUR
                  exchangeRate: '0.926480'
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
